### ISSUE TITLE
installing R in 10.11 (El Capitan)

### ISSUE THREAD

**Issue by smason** [Homebrew/homebrew-science#2512]
I've just tried installing R on a system recently upgraded to 10.11.  I had a couple of issues while building it but not sure where a good place to report them, so putting them here!

The first issue was `src/modules/lapack/vecLibg95c.c` not compiling with an error about not including `vecLib` directly—which R obviously doesn't.  I tracked this back to `/System/Frameworks` looking to be in a strange state (i.e. this may be something fixed before the general release) and manually compiling with `-isysroot /Applications/Xcode-beta.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk`.  Not very clean.

Second issue was due to it not finding `pdflatex` which should have been on the path.  I manually hacked a couple of Makefiles to set `PDFLATEX` pointing at the right place.

Hope that helps somebody else/I can be pointed to a better solution!

**Comment by tdsmith** [comment]
Thanks for the report.

> I tracked this back to /System/Frameworks looking to be in a strange state

Can you provide more detail about this?

> Second issue was due to it not finding pdflatex which should have been on the path. I manually hacked a couple of Makefiles to set PDFLATEX pointing at the right place.

When did this arise? I didn't think these were needed for a stable build.

**Comment by smason** [comment]
tim smith wrote:
> > I tracked this back to /System/Frameworks looking to be in a
> > strange state
> 
> Can you provide more detail about this?

As in using the default Accelerate framework can only fail.  I tried
just creating a simple C program that only includes Accelerate and it
fails to make sure I was understanding it correctly.  Within
`/System/Frameworks`, `<Accelerate/Accelerate.h>` basically just does

    #ifndef __VECLIB__
    #include <vecLib/vecLib.h>
    #endif

and `vecLib.h` just does:

    #error "The vecLib framework is deprecated. Please include <Accelerate/Accelerate.h> instead of <vecLib/vecLib.h> and link to the Accelerate framework instead of the vecLib framework."

hence me saying it's strange/broken.  The `Accelerate` in
`MacOSX10.11.sdk` looks much better, and directly refers to the
`vecLib` from "inside" itself (a subframework?), i.e.:

    #ifndef __VECLIB__
    #include "../Frameworks/vecLib.framework/Headers/vecLib.h"
    #endif

Looking at `Accelerate.h` from another computer that still has 10.10,
it looks like my new one but somehow knows how to build using the
subframework.  I therefore guess it's temporary breakage, but wanted
to post because other people may be affected by this issue.

> > Second issue was due to it not finding pdflatex which should have
> > been on the path. I manually hacked a couple of Makefiles to set
> > PDFLATEX pointing at the right place.
> 
> When did this arise? I didn't think these were needed for a stable build.

The build was failing on `NOTES.pdf` and some docs within required
packages (I think), so I was `make`ing by hand which failed due to
`$PDFLATEX` being defined to be empty within the Makefiles.  Not sure
if the issue is caused by this, but I installed MacTeX from scratch
inside this system, due to me breaking the new security restrictions
of writing in `/usr`.  `pdflatex` currently appears on my path in
`/Library/TeX/texbin` and this doesn't appear on the path when
building R.  Is this due to `superenv`?

This may all go away when 10.11 comes out properly, so not sure if
it's worth spending too much time on this.

Thanks,
  Sam

**Comment by imanuelcostigan** [comment]
I'm also getting an error:

```
imanuel@air:~$ brew install R
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing r from homebrew/homebrew-science
==> Installing dependencies for homebrew/science/r: glib, cairo
==> Installing homebrew/science/r dependency: glib
==> Downloading https://download.gnome.org/sources/glib/2.44/glib-2.44.1.tar.xz
Already downloaded: /Library/Caches/Homebrew/glib-2.44.1.tar.xz
==> Downloading https://gist.githubusercontent.com/jacknagel/af332f42fae80c570a77/raw/7b5f
Already downloaded: /Library/Caches/Homebrew/glib--patch-a4cb96b5861672ec0750cb30ecebe1d417d38052cac12fbb8a77dbf04a886fcb.diff
==> Downloading https://gist.githubusercontent.com/jacknagel/9835034/raw/282d36efc126272f3
Already downloaded: /Library/Caches/Homebrew/glib--patch-d285c70cfd3434394a1c77c92a8d2bad540c954aad21e8bb83777482c26aab9a.patch
==> Patching
patching file gio/gdbusprivate.c
Hunk #1 succeeded at 2117 (offset 18 lines).
Hunk #2 succeeded at 2127 (offset 18 lines).
patching file gio/xdgmime/xdgmime.c
patching file glib/gutils.c
patching file gio/Makefile.am
Hunk #2 succeeded at 526 (offset 10 lines).
patching file gio/Makefile.in
Hunk #2 succeeded at 162 (offset 2 lines).
Hunk #3 succeeded at 307 (offset 4 lines).
Hunk #4 succeeded at 3498 (offset 62 lines).
patching file gio/gnextstepsettingsbackend.c
patching file gio/gnextstepsettingsbackend.m
==> ./configure --disable-maintainer-mode --disable-silent-rules --disable-dtrace --disabl
==> make
make[4]: *** Waiting for unfinished jobs....
make[3]: *** [all-recursive] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting

These open issues may also help:
Glib-Networking fails to build on 10.9 (https://github.com/Homebrew/homebrew/issues/36323)
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
```


NB: I have chown'd /usr/local recursively and disabled root protections.

**Comment by smason** [comment]
I see you've reported quite a few issues related to 10.11.  You probably want to get smaller programs with less dependencies working before trying things like R—i.e. `fish` just worked for me once I'd got my build system updated but you've reported errors.

I'd not recommend leaving the `boot-args` `rootless=0` set, I certainly don't have it set and everything is working well.  I think you only need to set it if you deleted `/usr/local` and need to recreate it—have a look at:  https://github.com/Homebrew/homebrew/issues/40837#issuecomment-120762533 for more details.

**Comment by imanuelcostigan** [comment]
@smason I managed to install fish after installing xcode 7 beta.

**Comment by smason** [comment]
Running with `debug` and `verbose` helped me to figure out what was happening…  i.e.

    brew install -vd R

will let you see more output as well as drop to a shell on an error.  I hope my error was due to framework issues that will get fixed by apple.

**Comment by imanuelcostigan** [comment]
Ok it built and installed.

**Comment by tdsmith** [comment]
I built R successfully without modification on 10.11 Public Beta 1 and Xcode Command Line Tools 7.0.0.0.1.1436025195 so I'll close this issue. Thanks for the report!

**Comment by smason** [comment]
Yes, I can confirm this works for me now with latest CLTs.  I've got version 7.0.0.0.1.1437113798 though, as reported by:

    pkgutil --pkg-info=com.apple.pkg.CLTools_Executables

**Comment by WillyWinkel** [comment]
I think I still have issues with home-brew and R.
See https://gist.github.com/anonymous/e9e6ab1e46a128f8d860 in `02.make` from line 704 onwards.
I found the following that helped me https://github.com/Homebrew/homebrew/issues/42542, here they solved the problem by installing Xcode 7 and then run 
`sudo xcode-select -switch /Applications/Xcode-beta.app`
which removed the error.

**Comment by tdsmith** [comment]
Yes, you need to use the new Xcode (or the new CLT) on 10.11.

**Comment by gothicpurple** [comment]
The latest CLT are pretty useless without the latest XCode to install R.
I'm running El Captain Public Beta 4, CLT version 7.0.0.0.1.1438729353 but i don't have the new XCode 7 Beta and i'm experiencing the make-error as reported before.

**Comment by gothicpurple** [comment]
Even with XCode 7.0.1 and the latest CLT, i'm unable to install R on El Capitan.
"conftest quit unexpectedly" another error during the make process
